#!/usr/bin/env python3
"""
Reads Xcode Localizable.xcstrings and writes legacy Localizable.strings files
(one per locale) for SwiftGen. Keeps the String Catalog as the source of truth.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def escape_strings_value(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


def string_unit_value(entry_locale: object) -> str | None:
    if not isinstance(entry_locale, dict):
        return None
    unit = entry_locale.get("stringUnit")
    if not isinstance(unit, dict):
        return None
    val = unit.get("value")
    return val if isinstance(val, str) else None


def resolve_value(
    key: str,
    locale: str,
    localizations: dict,
    source_language: str,
) -> str:
    loc = localizations.get(locale)
    v = string_unit_value(loc) if loc else None
    if v is not None:
        return v
    src = localizations.get(source_language)
    v = string_unit_value(src) if src else None
    if v is not None:
        return v
    for loc_data in localizations.values():
        v = string_unit_value(loc_data)
        if v is not None:
            return v
    return key


def main() -> None:
    args = [a for a in sys.argv[1:] if a != "--all-locales"]
    all_locales = len(sys.argv[1:]) != len(args)
    if len(args) != 2:
        print(
            "usage: xcstrings_to_swiftgen_strings.py [--all-locales] <Localizable.xcstrings> <output_root>",
            file=sys.stderr,
        )
        sys.exit(1)
    xcstrings_path = Path(args[0]).resolve()
    out_root = Path(args[1]).resolve()
    data = json.loads(xcstrings_path.read_text(encoding="utf-8"))
    source_language = data.get("sourceLanguage") or "en"
    strings = data.get("strings")
    if not isinstance(strings, dict):
        print("error: invalid xcstrings (missing strings object)", file=sys.stderr)
        sys.exit(1)

    locales: set[str] = set()
    for entry in strings.values():
        if not isinstance(entry, dict):
            continue
        locs = entry.get("localizations")
        if isinstance(locs, dict):
            locales.update(locs.keys())
    if not locales:
        locales.add(source_language)

    if all_locales:
        ordered_locales = sorted(locales, key=lambda x: (0 if x == source_language else 1, x))
    else:
        primary = source_language if source_language in locales else sorted(locales)[0]
        ordered_locales = [primary]

    out_root.mkdir(parents=True, exist_ok=True)
    header = (
        "/* Generated by xcstrings_to_swiftgen_strings.py — do not edit by hand */\n"
        f"/* Source: {xcstrings_path.name} */\n\n"
    )

    for locale in ordered_locales:
        lproj = out_root / f"{locale}.lproj"
        lproj.mkdir(parents=True, exist_ok=True)
        lines: list[str] = [header.rstrip("\n")]
        for key in sorted(strings.keys()):
            entry = strings[key]
            localizations = entry.get("localizations") if isinstance(entry, dict) else None
            if not isinstance(localizations, dict):
                localizations = {}
            value = resolve_value(key, locale, localizations, source_language)
            lines.append(f'"{escape_strings_value(key)}" = "{escape_strings_value(value)}";')
        lines.append("")
        (lproj / "Localizable.strings").write_text("\n".join(lines) + "\n", encoding="utf-8")

    mode = "all locales" if all_locales else f"source locale only ({ordered_locales[0]})"
    print(f"xcstrings_to_swiftgen_strings: wrote {len(ordered_locales)} locale(s) ({mode}) → {out_root}")


if __name__ == "__main__":
    main()
